### ISSUE TITLE
Pressing shift while not in a world or server causes a crash

### ISSUE THREAD

**Issue by Kneelawk** [grondag/fermion#3] opened 2020-12-14 10:38 UTC
It appears that the ModKeysHandler does not check if the player is currently connected to a server before attempting to send a packet. This causes a crash if pressing any modifier key while not in a game. I encountered this bug while attempting to enter the name of a server into the server add dialog.

Let me know if you need any more details or if you're unable to reproduce the bug. :)

**Comment by grondag** [comment] 2020-12-14 17:26
Duplicate of #2 .  This is fixed as of yesterday or so.   If you have a mod that bundles an earlier version of Fermion then you'll need to put the latest curse forge release in your mods folder.

**Closed as completed by grondag** 2020-12-14 17:26 UTC
Labels: duplicate
